/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package umgboca1;
import java.util.HashSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author salaz
 */
public class FRM_PERSONAS extends javax.swing.JFrame {
    Cliente cliente;
 DefaultTableModel tbl_modelo;

    /**
     * Creates new form FRM_PERSONAS
     */
    
    public FRM_PERSONAS() {
        initComponents();
        cliente = new Cliente();
        tbl_modelo = new DefaultTableModel();
        String encabezado[]={"Nit","Nombres","Apellidos","Direccion","Telefono","FechaNacimiento"};
        tbl_modelo.setColumnIdentifiers(encabezado);
        tbl_Clientes.setModel(tbl_modelo);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tab_Principal = new javax.swing.JTabbedPane();
        Panel_Cliente = new javax.swing.JPanel();
        lbl_Nit = new javax.swing.JLabel();
        txt_nit = new javax.swing.JTextField();
        lbl_Nombres = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();
        lbl_Apellidos = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        lbl_Direccion = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        lbl_NumeroTel = new javax.swing.JLabel();
        txt_NumeroTel = new javax.swing.JTextField();
        lbl_FechaNacimiento = new javax.swing.JLabel();
        txt_FechadeNacimiento = new javax.swing.JTextField();
        btn_Guardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Clientes = new javax.swing.JTable();
        lbl_Mensaje = new javax.swing.JLabel();
        btn_Remove = new javax.swing.JButton();
        txt_Delet = new javax.swing.JTextField();
        btn_modificar = new javax.swing.JButton();
        Panel_Empleados = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Nit.setText("Nit");

        lbl_Nombres.setText("Nombres");

        txt_nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombresActionPerformed(evt);
            }
        });

        lbl_Apellidos.setText("Apellidos");

        lbl_Direccion.setText("Dirección");

        lbl_NumeroTel.setText("Numero Telefonico");

        lbl_FechaNacimiento.setText("Fecha de Nacimiento");

        btn_Guardar.setText("Guardar");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });

        tbl_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_Clientes);

        lbl_Mensaje.setText("Mensaje");

        btn_Remove.setText("Remove");
        btn_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RemoveActionPerformed(evt);
            }
        });

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_ClienteLayout = new javax.swing.GroupLayout(Panel_Cliente);
        Panel_Cliente.setLayout(Panel_ClienteLayout);
        Panel_ClienteLayout.setHorizontalGroup(
            Panel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ClienteLayout.createSequentialGroup()
                .addGroup(Panel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_ClienteLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(Panel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_ClienteLayout.createSequentialGroup()
                                .addGroup(Panel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Nit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_Apellidos)
                                    .addComponent(lbl_Direccion)
                                    .addComponent(lbl_NumeroTel)
                                    .addComponent(lbl_FechaNacimiento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Panel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_nombres)
                                        .addComponent(txt_apellidos)
                                        .addComponent(txt_direccion)
                                        .addComponent(txt_NumeroTel)
                                        .addComponent(txt_FechadeNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                                    .addGroup(Panel_ClienteLayout.createSequentialGroup()
                                        .addComponent(txt_nit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_modificar))))))
                    .addGroup(Panel_ClienteLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btn_Guardar)
                        .addGap(134, 134, 134)
                        .addComponent(lbl_Mensaje)
                        .addGap(72, 72, 72)
                        .addComponent(btn_Remove)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Delet, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        Panel_ClienteLayout.setVerticalGroup(
            Panel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ClienteLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Panel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Nit)
                    .addComponent(txt_nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modificar))
                .addGap(26, 26, 26)
                .addGroup(Panel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Nombres)
                    .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Panel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Apellidos))
                .addGap(28, 28, 28)
                .addGroup(Panel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Direccion)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_NumeroTel)
                    .addComponent(txt_NumeroTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_FechaNacimiento)
                    .addComponent(txt_FechadeNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(Panel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Guardar)
                    .addComponent(lbl_Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Remove)
                    .addComponent(txt_Delet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Tab_Principal.addTab("Cliente", Panel_Cliente);

        javax.swing.GroupLayout Panel_EmpleadosLayout = new javax.swing.GroupLayout(Panel_Empleados);
        Panel_Empleados.setLayout(Panel_EmpleadosLayout);
        Panel_EmpleadosLayout.setHorizontalGroup(
            Panel_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 889, Short.MAX_VALUE)
        );
        Panel_EmpleadosLayout.setVerticalGroup(
            Panel_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        Tab_Principal.addTab("Empleado", Panel_Empleados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tab_Principal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Tab_Principal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombresActionPerformed

    
    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        // TODO add your handling code here:
        //System.out.println("Hola");
         //this.lbl_Mensaje.setText("Hola");
        cliente.setNit(txt_nit.getText());
        cliente.setNombres(txt_nombres.getText());
        cliente.setApellidos(txt_apellidos.getText());
        cliente.setDireccion(txt_direccion.getText());
        cliente.setTelefono(txt_NumeroTel.getText());
        cliente.setFecha_de_Nacimiento(txt_FechadeNacimiento.getText());
        
       
        cliente.crearArrayYllenarlo();
        tbl_modelo.addRow(cliente.crearArrayYllenarlo());
        tbl_Clientes.setModel(tbl_modelo);
    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void btn_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RemoveActionPerformed
        // TODO add your handling code here:
        
        String borrar = txt_Delet.getText();
        int borrarConvertido = Integer.parseInt(borrar);
        
        tbl_modelo.removeRow(borrarConvertido - 1);
        
    }//GEN-LAST:event_btn_RemoveActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
        cliente.setNit(txt_nit.getText());
        tbl_modelo.addRow(cliente.crearArrayYllenarlo());
        tbl_Clientes.setModel(tbl_modelo);
    }//GEN-LAST:event_btn_modificarActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_PERSONAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_PERSONAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_PERSONAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_PERSONAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_PERSONAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Cliente;
    private javax.swing.JPanel Panel_Empleados;
    private javax.swing.JTabbedPane Tab_Principal;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_Remove;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Apellidos;
    private javax.swing.JLabel lbl_Direccion;
    private javax.swing.JLabel lbl_FechaNacimiento;
    private javax.swing.JLabel lbl_Mensaje;
    private javax.swing.JLabel lbl_Nit;
    private javax.swing.JLabel lbl_Nombres;
    private javax.swing.JLabel lbl_NumeroTel;
    private javax.swing.JTable tbl_Clientes;
    private javax.swing.JTextField txt_Delet;
    private javax.swing.JTextField txt_FechadeNacimiento;
    private javax.swing.JTextField txt_NumeroTel;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nit;
    private javax.swing.JTextField txt_nombres;
    // End of variables declaration//GEN-END:variables
}
